#!/usr/bin/env bash
# installation and running html page using nginx

sudo apt-get update -y
sudo apt-get install nginx -y
sudo ufw allow 'nginx HTTP'

echo "Hello World!" > /var/www/html/index.nginx-debian.html

sudo service nginx reload
