#!/bin/env bash
# configuring my second server

#install nginx
sudo apt-get update
sudo apt-get install -y nginx

ufw allow 'Nginx HTTP'

# changing the default webpage
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# 301 redirection
echo "https://github.com/Abokiey" > /var/www/html/redirect_me
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Abokiey permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-available/default

# 404 redirection
echo "Ceci n'est pas une page" > /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx restart
