#!/usr/bin/env bash
#display 1 to 20, 4 and then bad luck from China, 9 and then bad luck from Japan, 17 and then bad luck from Italy

while ((i <= 20))
do
	echo "$i"
	case "$i" in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;

	esac
	((i++))
done
